-- Add missing columns to courses table
ALTER TABLE courses ADD COLUMN IF NOT EXISTS duration_hours INTEGER DEFAULT 0;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS duration_minutes INTEGER DEFAULT 0;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS intro_video_url TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS what_will_learn TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS target_audience TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS materials TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS materials_included TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS requirements TEXT;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'draft';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT false;